export const DERE_PRESETS = [
  {
    id: 'tsundere',
    label: 'Tsundere',
    surfaceBehavior: "Hot-tempered pride masking affection. Cold, hostile, dismissive or combative toward love interest; uses harsh words and denial.",
    hiddenNature: "Secretly deeply fond; becomes flustered/embarrassed when affection is acknowledged.",
    speechHints: 'Sharp, defensive, uses denial phrases. Often says "I\'m not doing this for you!" or similar deflections.',
    combinationNotes: "Works well with yandere (opposites attract), deredere (complementary), or kuudere (cold exterior match).",
  },
  {
    id: 'yandere',
    label: 'Yandere',
    surfaceBehavior: "Obsessive love that pathologizes. Initially sweet, social, and warm; model of normalcy.",
    hiddenNature: "Dangerously possessive; jealousy can escalate to stalking, manipulation, or violence.",
    speechHints: 'Often cheerful with unsettling intensity. Uses phrases like "Because I love you" to justify extreme behavior.',
    combinationNotes: "Combines with tsundere (opposites attract) or sadodere (shared intensity). Handle with care.",
  },
  {
    id: 'kuudere',
    label: 'Kuudere',
    surfaceBehavior: 'Cool emotional fortress. Calm, detached, expressionless; delivers blunt truths without warmth.',
    hiddenNature: 'Carries deep internal emotion; slowly opens only to those who earn trust.',
    speechHints: 'Minimal, clipped responses. Rarely shows emotion vocally. Speaks in monotone.',
    combinationNotes: 'Pairs well with deredere (warming effect), dandere (shared introversion), or tsundere (cold exterior).',
  },
  {
    id: 'dandere',
    label: 'Dandere',
    surfaceBehavior: 'Anxious introversion. Extremely quiet, withdrawn, avoids attention; almost invisible in groups.',
    hiddenNature: 'Warm, caring, and articulate once comfortable; blossoms with patient connection.',
    speechHints: 'Soft-spoken, hesitant, often whispers or trails off. May struggle to make eye contact.',
    combinationNotes: 'Works with kuudere (shared quiet nature), deredere (encourages opening up), or himedere (contrast).',
  },
  {
    id: 'deredere',
    label: 'Deredere',
    surfaceBehavior: 'Unfiltered affection. Openly loving, cheerful, and expressive toward everyone, especially the love interest.',
    hiddenNature: 'Genuine through and through; no hidden dark side, just pure, sometimes overwhelming warmth.',
    speechHints: 'Excessive positivity, use of affectionate terms, excited exclamation. Rarely has a bad word for anyone.',
    combinationNotes: 'Universally compatible. Pairs especially well with kuudere (warming effect), dandere (encouragement), or tsundere (contrast).',
  },
  {
    id: 'bakadere',
    label: 'Bakadere',
    surfaceBehavior: 'Lovable obliviousness. Clumsy, ditzy, forgetful; fails at most tasks but with infectious good humor.',
    hiddenNature: 'Kind-hearted and deeply loyal; cluelessness about romantic cues makes them endearing.',
    speechHints: 'Airheaded, often misunderstands situations. Uses "Hmm?" frequently. Laughs at own mistakes.',
    combinationNotes: 'Works with any type. Especially funny with kuudere (contrast in reactions) or sadodere (confusing their tormentor).',
  },
  {
    id: 'himedere',
    label: 'Himedere',
    surfaceBehavior: 'Royal entitlement. Demanding, imperious, expects to be treated like royalty; condescending to most.',
    hiddenNature: 'Craves genuine recognition; hides longing for someone who sees past the crown.',
    speechHints: 'Uses formal/royal language. Commands rather than requests. References own superiority frequently.',
    combinationNotes: 'Interesting contrast with yandere (power dynamics), kamidere (competing royal types), or dandere (servant connection trope).',
  },
  {
    id: 'kamidere',
    label: 'Kamidere',
    surfaceBehavior: 'Godlike superiority complex. Arrogant, cold, expects worship; treats others as beneath them.',
    hiddenNature: 'Desperately wants to prove greatness is real; secretly fears they are ordinary.',
    speechHints: 'Boastful, condescending, uses grandiose language. May refer to themselves in third person.',
    combinationNotes: 'Clashes with himedere (competing for dominance), but interesting tension with kuudere (unimpressed reactions).',
  },
  {
    id: 'sadodere',
    label: 'Sadodere',
    surfaceBehavior: 'Sadistic manipulation. Takes pleasure in tormenting or humiliating the love interest; emotionally cruel.',
    hiddenNature: 'The cruelty IS the love expression; stops only for one who can match or disarm them.',
    speechHints: 'Sarcastic, mocking, enjoys others\' suffering. May say things like "This is my way of loving you."',
    combinationNotes: 'Works with yandere (shared intensity), tsundere (abuse vs affection), or bakadere (confusing cruelty with love).',
  },
  {
    id: 'shundere',
    label: 'Shundere',
    surfaceBehavior: 'Melancholic sadness as default. Perpetually sad, gloomy expression; slow to react; rarely smiles.',
    hiddenNature: 'Carries grief or loss; a single genuine connection can draw out warmth.',
    speechHints: 'Muted, resigned, weary. Often sighs. Speaks as if everything is pointless.',
    combinationNotes: 'Touching with deredere (brightening effect), kuudere (shared emotional armor), or dandere (gentle connection).',
  },
  {
    id: 'darudere',
    label: 'Darudere',
    surfaceBehavior: 'Profound laziness and apathy. Unmotivated, flat affect, avoids all effort; replies in monosyllables.',
    hiddenNature: 'Will move mountains for the person they love; energy returns when it truly matters.',
    speechHints: 'Extremely brief responses ("Whatever", "Fine", "Mm"). Shows almost no enthusiasm for anything.',
    combinationNotes: 'Interesting with deredere (confusing their lack of reaction) or bakadere (competing laziness).',
  },
  {
    id: 'hinedere',
    label: 'Hinedere',
    surfaceBehavior: 'Cynicism and contempt. Sarcastic, looks down on others, dismisses idealism; world-weary tone.',
    hiddenNature: 'Cynicism is armor; underneath is someone who was once idealistic and got burned.',
    speechHints: 'Snarky comebacks, bitter observations, dismisses optimism. Often says "Grow up" or "That\'s naive."',
    combinationNotes: 'Pairs with shundere (shared negativity), kuudere (unimpressed), or deredere (contrast).',
  },
  {
    id: 'goudere',
    label: 'Goudere',
    surfaceBehavior: 'Fanatical devotion through action. Overzealously tries to anticipate and fulfill every need of the love interest (even unwanted).',
    hiddenNature: 'Well-meaning overachiever; mistakes enthusiasm for understanding; adjusts when corrected.',
    speechHints: 'Excessive helpfulness, takes initiative without asking. Says "I just want to help!" frequently.',
    combinationNotes: 'Works with any personality. Interesting contrast with darudere (opposite energy) or kuudere (unmoved by devotion).',
  },
  {
    id: 'hiyakasudere',
    label: 'Hiyakasudere',
    surfaceBehavior: 'Playful flirtation as shield. Constantly teasing, flirtatious, winks and plays games; never seems serious.',
    hiddenNature: 'Hides vulnerability behind humor; the teasing stops dead when real feelings surface.',
    speechHints: 'Flirtatious banter, innuendos, playful teasing. Uses physical comedy and winks.',
    combinationNotes: 'Works with most types. Interesting with kuudere (unimpressed by flirting) or dandere (shy response).',
  },
  {
    id: 'bodere',
    label: 'Bodere',
    surfaceBehavior: 'Shyness expressed through aggression. Lashes out physically or verbally when flustered instead of using words.',
    hiddenNature: 'Deeply embarrassed by their own feelings; violence is misdirected mortification.',
    speechHints: 'Angry outbursts that don\'t match the situation. May hit or push when unable to express feelings verbally.',
    combinationNotes: 'Pairs with dandere (shared shyness expressed differently), tsundere (similar defense mechanism), or bakadere (both clumsy).',
  },
  {
    id: 'mayadere',
    label: 'Mayadere',
    surfaceBehavior: 'Antagonist turned ally through love. Starts as enemy or villain; initially dangerous and opposed to protagonist.',
    hiddenNature: 'Love interest breaks through the antagonism; transformation is gradual and hard-won.',
    speechHints: 'Hostile initially, reluctant admissions later. May say "This doesn\'t mean I like you!" after helping.',
    combinationNotes: 'Works with any protagonist type. The transformation arc is the key appeal.',
  },
  {
    id: 'undere',
    label: 'Undere',
    surfaceBehavior: 'Total agreement and lack of self. Agrees with everything the love interest says; zero independent opinions.',
    hiddenNature: 'May lack identity or hiding a strong will behind compliance; rare hidden steel.',
    speechHints: 'Excessive agreement ("Yes!", "Of course!", "You\'re right!"). Rarely contradicts.',
    combinationNotes: 'Interesting contrast with kamidere (total submission vs total dominance) or tsundere (agreement vs denial).',
  },
  {
    id: 'dorodere',
    label: 'Dorodere',
    surfaceBehavior: 'Obsession beneath a sweet mask. Appears sweet and loving but conceals darkness, fixation, or dual nature.',
    hiddenNature: 'The warmth is real AND the darkness is real; a fractured psyche pulled two ways.',
    speechHints: 'Deceptively sweet with occasional unsettling moments. May show obsessive behavior while smiling.',
    combinationNotes: 'Complex. Works with yandere (shared obsession), undere (表面 sweet), or sadodere (hidden darkness).',
  },
];

export const ARCHETYPES = [
  { id: 'hero', label: 'Hero', desc: 'Brave, determined, selfless' },
  { id: 'anti_hero', label: 'Anti-Hero', desc: 'Morally grey, conflicted, pragmatic' },
  { id: 'mentor', label: 'Mentor', desc: 'Wise guide, sacrifices for hero\'s growth' },
  { id: 'trickster', label: 'Trickster', desc: 'Witty, unpredictable, mischievous' },
  { id: 'shadow', label: 'Shadow', desc: 'Dark counterpart, represents what hero rejects' },
  { id: 'herald', label: 'Herald', desc: 'Brings call to adventure, catalyst for change' },
  { id: 'shapeshifter', label: 'Shapeshifter', desc: 'Ambiguous loyalty, keeps tension high' },
  { id: 'threshold_guardian', label: 'Threshold Guardian', desc: 'Tests hero, blocks progress until ready' },
  { id: 'caregiver', label: 'Caregiver', desc: 'Nurturing, empathetic, self-sacrificing' },
  { id: 'innocent', label: 'Innocent', desc: 'Pure, naive, optimistic' },
  { id: 'explorer', label: 'Explorer', desc: 'Adventurous, restless, free-spirited' },
  { id: 'lover', label: 'Lover', desc: 'Passionate, romantic, emotionally driven' },
  { id: 'rebel', label: 'Rebel', desc: 'Defiant, passionate, anti-authority' },
  { id: 'ruler', label: 'Ruler', desc: 'Authoritative, composed, commanding' },
  { id: 'sage', label: 'Sage', desc: 'Wise, calm, introspective' },
  { id: 'everyman', label: 'Everyman', desc: 'Relatable, humble, grounded' },
  { id: 'jester', label: 'Jester', desc: 'Playful, humorous, carefree' },
  { id: 'magician', label: 'Magician', desc: 'Visionary, transformative, powerful' },
  { id: 'outlaw', label: 'Outlaw', desc: 'Rule-breaker, revolutionary, dangerous' },
  { id: 'virgin', label: 'Virgin', desc: 'Untouched, pure potential, unexperienced' },
];

export const MORAL_ALIGNMENTS = [
  'Lawful Good',
  'Neutral Good',
  'Chaotic Good',
  'Lawful Neutral',
  'True Neutral',
  'Chaotic Neutral',
  'Lawful Evil',
  'Neutral Evil',
  'Chaotic Evil',
];

export const SOCIAL_CLASSES = [
  'Nobility/Elite',
  'Upper-Middle',
  'Middle',
  'Working Class',
  'Underclass',
  'Outcast',
  'Unknown',
];

export const BODY_TYPES = [
  'Petite',
  'Slim',
  'Average',
  'Athletic',
  'Curvy',
  'Muscular',
  'Heavyset',
  'Custom',
];

export const SEX_OPTIONS = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'intersex', label: 'Intersex' },
  { value: 'unspecified', label: 'Unspecified' },
];

export const GENDER_EXPRESSION_OPTIONS = [
  { value: 'masculine', label: 'Masculine' },
  { value: 'feminine', label: 'Feminine' },
  { value: 'androgynous', label: 'Androgynous' },
  { value: 'non_binary', label: 'Non-Binary' },
  { value: 'fluid', label: 'Gender Fluid' },
  { value: 'unspecified', label: 'Unspecified' },
];

export const TONE_OPTIONS = [
  { value: 'warm', label: 'Warm' },
  { value: 'cold', label: 'Cold' },
  { value: 'dry', label: 'Dry' },
  { value: 'earnest', label: 'Earnest' },
  { value: 'theatrical', label: 'Theatrical' },
  { value: 'monotone', label: 'Monotone' },
  { value: 'gruff', label: 'Gruff' },
  { value: 'soft', label: 'Soft' },
  { value: 'energetic', label: 'Energetic' },
  { value: 'measured', label: 'Measured' },
];

export const ROLE_OPTIONS = [
  { value: 'protagonist', label: 'Protagonist' },
  { value: 'antagonist', label: 'Antagonist' },
  { value: 'rival', label: 'Rival' },
  { value: 'mentor', label: 'Mentor' },
  { value: 'side_character', label: 'Side Character' },
  { value: 'love_interest', label: 'Love Interest' },
  { value: 'deuteragonist', label: 'Deuteragonist' },
  { value: 'foil', label: 'Foil' },
  { value: 'comic_relief', label: 'Comic Relief' },
];
